### ISSUE TITLE
Cloud Guide for Google Vertex AI Workbench

### ISSUE THREAD

**Issue by NOT-HAL9000** [victorchall/EveryDream2trainer#104]
Would love to give this a try in the Google Cloud Platform ecosystem (with logging).

**Comment by victorchall** [comment]
Not familiar with Vertex. A brief look it seems you can use a custom docker container which is provided for ED2 and linked on the  main readme, then you should be able to open up the existing Train_JupyterNotebook.ipnb from there, but I don't have time to offer support for more platforms at this time.

Or you can just use Colab.  You can use the T4 or A100.  T4 is cost effective.  By default your tensorboard logs are sent over to your gdrive or you can use wandb.
