### ISSUE TITLE
Training crash on large dataset

### ISSUE THREAD

**Issue by aptecoSmith** [victorchall/EveryDream2trainer#109]
I am attempting to train a model using 100k plus images.

I appear to be trying to use more VRAM then I have after about 4 hours, which does not make a lot of sense to me.

Stack Trace attached.
Any insight would be much appreciated!

[error.txt](https://github.com/victorchall/EveryDream2trainer/files/10929346/error.txt)

**Comment by victorchall** [comment]
I've tested up to 125000 images (all of Coco2017) and had a steady 25GB of system RAM use.  Are you using latest version?  I did fix a memory leak about 2 weeks ago.

The error is system memory, not VRAM.  It is dying trying to save a checkpoint, which temporarily uses extra system memory but its only a few gigabytes.  On discord you said you had 56GB of system memory which is plenty.

You might make sure you have a swap file setup, but I would think 56GB should be plenty.

**Comment by aptecoSmith** [comment]
Thanks @victorchall  - I think my version was older than 2 weeks so I have pulled today.  I've increased page file to 64gb minimum to 100gb max and am running again.  Some comment sin the discord regarding large ram usage when ckpt is being saved, so I'm hoping these two fixes fix the issue!  Very much appreciate you taking a look.

**Comment by victorchall** [comment]
![image](https://user-images.githubusercontent.com/15839076/224335966-7b0c0f4d-8235-44f2-a122-d6df9c46daa2.png)
This was fixed about 2 weeks ago, should be good to 200k+ on 56GB without doing anything to swap file.  Haven't limit tested but maybe even far more.   Only metadata about your images/training data is kept in memory after the fix.
