### ISSUE TITLE
[ERROR] --shuffle_tags is broken (error occurs on runpod)

### ISSUE THREAD

**Issue by hopto-dot** [victorchall/EveryDream2trainer#121]
### **Attach log and cfg**
* [log file](https://github.com/victorchall/EveryDream2trainer/files/11068641/Model-Name-768x768-F0-20230325-102554.log)
* [json file](https://github.com/victorchall/EveryDream2trainer/files/11068651/Model-Name-768x768-F0-20230325-102554_cfg.txt)

### **Runtime environment:**
 - **OS:** Some Linux distro
 - **Is this your local computer or a cloud host?**  Runpod
 - **GPU:** RTX 3090

### **Additional context**
--shuffle_tags consistently fails to work on runpod (i.e. training doesn't start).

**The exact output of the error is:**

```
  No model to save, something likely blew up on startup, not saving
Traceback (most recent call last):
  File "/workspace/EveryDream2trainer/train.py", line 999, in <module>
    main(args)
  File "/workspace/EveryDream2trainer/train.py", line 924, in main
    raise ex
  File "/workspace/EveryDream2trainer/train.py", line 809, in main
    for step, batch in enumerate(train_dataloader):
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/workspace/venv/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/EveryDream2trainer/data/every_dream.py", line 101, in __getitem__
    example["caption"] = train_item["caption"].get_shuffled_caption(self.seed)
  File "/workspace/EveryDream2trainer/data/image_train_item.py", line 70, in get_shuffled_caption
    max_target_tag_length = self.__max_target_length - len(self.__main_prompt)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

Epochs:   0%|          | 0/150 [00:00<?, ?it/s, vram=5133/24576 MB gs:0] 
```

**Comment by wetgsg** [comment]
same here.

**Comment by victorchall** [comment]
Are either of you use local.yaml or global.yaml?

**Comment by wetgsg** [comment]
> Кто-то из вас использует local.yaml или global.yaml?
> 
> Qslug исправил ту же ошибку на прошлой неделе, я полагаю, это было недавно?

I just started the workout cell with the parameters I needed, I didn't do anything with the configs.

> Are either of you use local.yaml or global.yaml?
> 
> Qslug fixed the same error last week, I assume this was recent?

I just started the train cell with the parameters I needed, I didn't do anything with the configs.

**Comment by hopto-dot** [comment]
> Are either of you use local.yaml or global.yaml?
> 
> Qslug fixed the same error last week, I assume this was recent?

I'm not sure what you're referring to. But I start training on Jupyter lab through runpod, but use the console to actually start training - does that help?

**Comment by hopto-dot** [comment]
I also want to note that --shuffle_tags worked up until maybe a couple of weeks ago and I haven't changed the way I do training.

**Comment by victorchall** [comment]
I pushed a couple changes yesterday that might help, but not sure what is happening as I can't reproduce it.

If you can, watch your logs for "Error determining length for..." and it should print the first section of the caption that is the issue, it seems like there may be a specific caption that is causing problems for some reason.

**Comment by wetgsg** [comment]
> I pushed a couple changes yesterday that might help, but not sure what is happening as I can't reproduce it.
> 
> If you can, watch your logs for "Error determining length for..." and it should print the first section of the caption that is the issue, it seems like there may be a specific caption that is causing problems for some reason.
> 
> If you can figure out what image is causing "Error determining length for" and share the file/caption I can help further. It's something with the data. Or if you're willing to DM me a copy of your dataset on Discord I can try to reproduce.

I am getting an error when the training reaches the generation of samples.
NotImplementedError                       Traceback (most recent call last)
File /workspace/EveryDream2trainer/train.py:1010
   1008 print(f" Args:")
   1009 pprint.pprint(vars(args))
-> 1010 main(args)

File /workspace/EveryDream2trainer/train.py:936, in main(args)
    934     save_path = os.path.join(f"{log_folder}/ckpts/errored-{args.project_name}-ep{epoch:02}-gs{global_step:05}")
    935     __save_model(save_path, unet, text_encoder, tokenizer, noise_scheduler, vae, args.save_ckpt_dir, yaml, args.save_full_precision)
--> 936     raise ex
    938 logging.info(f"{Fore.LIGHTWHITE_EX} ***************************{Style.RESET_ALL}")
    939 logging.info(f"{Fore.LIGHTWHITE_EX} **** Finished training ****{Style.RESET_ALL}")

File /workspace/EveryDream2trainer/train.py:882, in main(args)
    879     torch.cuda.empty_cache()
    881 if (global_step + 1) % sample_generator.sample_steps == 0:
--> 882     generate_samples(global_step=global_step, batch=batch)
    884 min_since_last_ckpt =  (time.time() - last_epoch_saved_time) / 60
    886 if args.ckpt_every_n_minutes is not None and (min_since_last_ckpt > args.ckpt_every_n_minutes):

File /workspace/EveryDream2trainer/train.py:787, in main.<locals>.generate_samples(global_step, batch)
    784     print(f" * SampleGenerator config changed, now generating images samples every " +
    785           f"{sample_generator.sample_steps} training steps (next={next_sample_step})")
    786 sample_generator.update_random_captions(batch["captions"])
--> 787 inference_pipe = sample_generator.create_inference_pipe(unet=unet,
    788                                                         text_encoder=text_encoder,
    789                                                         tokenizer=tokenizer,
    790                                                         vae=vae,
    791                                                         diffusers_scheduler_config=reference_scheduler.config
    792                                                         ).to(device)
    793 sample_generator.generate_samples(inference_pipe, global_step)
    795 del inference_pipe

File /workspace/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File /workspace/EveryDream2trainer/utils/sample_generator.py:294, in SampleGenerator.create_inference_pipe(self, unet, text_encoder, tokenizer, vae, diffusers_scheduler_config)
    283 pipe = StableDiffusionPipeline(
    284     vae=vae,
    285     text_encoder=text_encoder,
   (...)
    291     feature_extractor=None, # must be None if no safety checker
    292 )
    293 if self.use_xformers:
--> 294     pipe.enable_xformers_memory_efficient_attention()
    295 return pipe

File /workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py:1080, in DiffusionPipeline.enable_xformers_memory_efficient_attention(self, attention_op)
   1050 def enable_xformers_memory_efficient_attention(self, attention_op: Optional[Callable] = None):
   1051     r"""
   1052     Enable memory efficient attention as implemented in xformers.
   1053 
   (...)
   1078     ```
   1079     """
-> 1080     self.set_use_memory_efficient_attention_xformers(True, attention_op)

File /workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py:1105, in DiffusionPipeline.set_use_memory_efficient_attention_xformers(self, valid, attention_op)
   1103 module = getattr(self, module_name)
   1104 if isinstance(module, torch.nn.Module):
-> 1105     fn_recursive_set_mem_eff(module)

File /workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py:1096, in DiffusionPipeline.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
   1094 def fn_recursive_set_mem_eff(module: torch.nn.Module):
   1095     if hasattr(module, "set_use_memory_efficient_attention_xformers"):
-> 1096         module.set_use_memory_efficient_attention_xformers(valid, attention_op)
   1098     for child in module.children():
   1099         fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:219, in ModelMixin.set_use_memory_efficient_attention_xformers(self, valid, attention_op)
    217 for module in self.children():
    218     if isinstance(module, torch.nn.Module):
--> 219         fn_recursive_set_mem_eff(module)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:215, in ModelMixin.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
    212     module.set_use_memory_efficient_attention_xformers(valid, attention_op)
    214 for child in module.children():
--> 215     fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:215, in ModelMixin.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
    212     module.set_use_memory_efficient_attention_xformers(valid, attention_op)
    214 for child in module.children():
--> 215     fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:215, in ModelMixin.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
    212     module.set_use_memory_efficient_attention_xformers(valid, attention_op)
    214 for child in module.children():
--> 215     fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:212, in ModelMixin.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
    210 def fn_recursive_set_mem_eff(module: torch.nn.Module):
    211     if hasattr(module, "set_use_memory_efficient_attention_xformers"):
--> 212         module.set_use_memory_efficient_attention_xformers(valid, attention_op)
    214     for child in module.children():
    215         fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:219, in ModelMixin.set_use_memory_efficient_attention_xformers(self, valid, attention_op)
    217 for module in self.children():
    218     if isinstance(module, torch.nn.Module):
--> 219         fn_recursive_set_mem_eff(module)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:215, in ModelMixin.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
    212     module.set_use_memory_efficient_attention_xformers(valid, attention_op)
    214 for child in module.children():
--> 215     fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:215, in ModelMixin.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
    212     module.set_use_memory_efficient_attention_xformers(valid, attention_op)
    214 for child in module.children():
--> 215     fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:212, in ModelMixin.set_use_memory_efficient_attention_xformers.<locals>.fn_recursive_set_mem_eff(module)
    210 def fn_recursive_set_mem_eff(module: torch.nn.Module):
    211     if hasattr(module, "set_use_memory_efficient_attention_xformers"):
--> 212         module.set_use_memory_efficient_attention_xformers(valid, attention_op)
    214     for child in module.children():
    215         fn_recursive_set_mem_eff(child)

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py:146, in CrossAttention.set_use_memory_efficient_attention_xformers(self, use_memory_efficient_attention_xformers, attention_op)
    140         _ = xformers.ops.memory_efficient_attention(
    141             torch.randn((1, 2, 40), device="cuda"),
    142             torch.randn((1, 2, 40), device="cuda"),
    143             torch.randn((1, 2, 40), device="cuda"),
    144         )
    145     except Exception as e:
--> 146         raise e
    148 if is_lora:
    149     processor = LoRAXFormersCrossAttnProcessor(
    150         hidden_size=self.processor.hidden_size,
    151         cross_attention_dim=self.processor.cross_attention_dim,
    152         rank=self.processor.rank,
    153         attention_op=attention_op,
    154     )

File /workspace/venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py:140, in CrossAttention.set_use_memory_efficient_attention_xformers(self, use_memory_efficient_attention_xformers, attention_op)
    137 else:
    138     try:
    139         # Make sure we can run the memory efficient attention
--> 140         _ = xformers.ops.memory_efficient_attention(
    141             torch.randn((1, 2, 40), device="cuda"),
    142             torch.randn((1, 2, 40), device="cuda"),
    143             torch.randn((1, 2, 40), device="cuda"),
    144         )
    145     except Exception as e:
    146         raise e

File /workspace/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py:196, in memory_efficient_attention(query, key, value, attn_bias, p, scale, op)
    115 def memory_efficient_attention(
    116     query: torch.Tensor,
    117     key: torch.Tensor,
   (...)
    123     op: Optional[AttentionOp] = None,
    124 ) -> torch.Tensor:
    125     """Implements the memory-efficient attention mechanism following
    126     `"Self-Attention Does Not Need O(n^2) Memory" <[http://arxiv.org/abs/2112.05682>`_](http://arxiv.org/abs/2112.05682%3E%60_).
    127 
   (...)
    194     :return: multi-head attention Tensor with shape ``[B, Mq, H, Kv]``
    195     """
--> 196     return _memory_efficient_attention(
    197         Inputs(
    198             query=query, key=key, value=value, p=p, attn_bias=attn_bias, scale=scale
    199         ),
    200         op=op,
    201     )

File /workspace/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py:294, in _memory_efficient_attention(inp, op)
    289 def _memory_efficient_attention(
    290     inp: Inputs, op: Optional[AttentionOp] = None
    291 ) -> torch.Tensor:
    292     # fast-path that doesn't require computing the logsumexp for backward computation
    293     if all(x.requires_grad is False for x in [inp.query, inp.key, inp.value]):
--> 294         return _memory_efficient_attention_forward(
    295             inp, op=op[0] if op is not None else None
    296         )
    298     output_shape = inp.normalize_bmhk()
    299     return _fMHA.apply(
    300         op, inp.query, inp.key, inp.value, inp.attn_bias, inp.p, inp.scale
    301     ).reshape(output_shape)

File /workspace/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py:310, in _memory_efficient_attention_forward(inp, op)
    308 output_shape = inp.normalize_bmhk()
    309 if op is None:
--> 310     op = _dispatch_fw(inp)
    311 else:
    312     _ensure_op_supports_or_raise(ValueError, "memory_efficient_attention", op, inp)

File /workspace/venv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py:98, in _dispatch_fw(inp)
     96     priority_list_ops.remove(triton.FwOp)
     97     priority_list_ops.insert(0, triton.FwOp)
---> 98 return _run_priority_list(
     99     "memory_efficient_attention_forward", priority_list_ops, inp
    100 )

File /workspace/venv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py:73, in _run_priority_list(name, priority_list, inp)
     71 for op, not_supported in zip(priority_list, not_supported_reasons):
     72     msg += "\n" + _format_not_supported_reasons(op, not_supported)
---> 73 raise NotImplementedError(msg)

NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    requires A100 GPU
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40

**Comment by wetgsg** [comment]
Also, I want to mention the warning at the very beginning of the training: WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu118 with CUDA 1108 (you have 1.13.1+cu117)
    Python  3.10.10 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

**Comment by victorchall** [comment]
@wetgsg please open another issue, your error above has nothing to do with tag shuffling

**Comment by victorchall** [comment]
This is long ago fixed.
