### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by wetgsg** [victorchall/EveryDream2trainer#128]
**Runtime environment (please complete the following information):**
 - OS: Linux
 - Is this your local computer or a cloud host?  Google Colab, free tier

**Additional context**
When I run the training cell, I receive the following error:
![image](https://user-images.githubusercontent.com/128916137/228798125-78623dc1-4f03-4f0d-9d6d-6f8ab1b528e7.png)

**Comment by victorchall** [comment]
![image](https://user-images.githubusercontent.com/15839076/228852391-3124008b-5bdb-41f0-9bdf-405c0102c19c.png)
