### ISSUE TITLE
Colab error - Get a base model

### ISSUE THREAD

**Issue by Rudy34160** [victorchall/EveryDream2trainer#135]
Hi, 

When I try to download an another model in th "Get a base model", I have this error : 

![image](https://user-images.githubusercontent.com/118270456/231812478-134a11af-d07b-47aa-bd2a-8fa15bcb1354.png)

**Comment by meganano202** [comment]
If you want to quick fix it while it get fixed, u can input the url/directory of ur model (.cpk) and the type of model in "Get A Base Model", then run it without enable "resume", when the log is made, u can just enable the resume option for the next time
