### ISSUE TITLE
[BUG] "Test your Diffusers" block at bottom of Google Colab generates black images

### ISSUE THREAD

**Issue by ansonkao** [victorchall/EveryDream2trainer#138]
Basically, the "Test your Diffusers" block at bottom of Google Colab generates black images, even with successfully trained .ckpt files (confirmed by the sample images generating nicely during training, and by using the .ckpt file in Automatic1111). 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/300092/231968786-63fb8f2d-3622-46f5-a798-748221a29d08.png">

This is on Google Colab with Premium GPU

Please report if this is happening to you as well!

**Comment by victorchall** [comment]
@nawnie

**Comment by victorchall** [comment]
Was this an SD1.x based model or SD2.1 ?

**Comment by ansonkao** [comment]
SD 2.1, maybe that's why
