### ISSUE TITLE
Colab - Resume CKPT

### ISSUE THREAD

**Issue by Rudy34160** [victorchall/EveryDream2trainer#139]
How can I integrate the information from the docs into the Colab notebook to resume training?

![image](https://user-images.githubusercontent.com/118270456/232021814-d3d7c3f1-d0c9-4d63-af40-5fb1601de47c.png)

**Comment by victorchall** [comment]
You can paste the location to your ckpt folder in your logs into the MODEL_LOCATION under "get a base model" like this: 
![image](https://user-images.githubusercontent.com/15839076/232177205-b68dfb7d-5186-4189-a383-9781d5350e55.png)

**Comment by victorchall** [comment]
You can browse in colab file gutter and click the three little dots next to the ckpt folder you want to resume from
![image](https://user-images.githubusercontent.com/15839076/232177246-5a550064-8a6b-489b-8d9e-ea4337022207.png)
