### ISSUE TITLE
[ERROR] ModuleNotFoundError: No module named 'compel'

### ISSUE THREAD

**Issue by meganano202** [victorchall/EveryDream2trainer#145]
I cant post log because it dont generate it but I posted a pic of the problem. The log below is the one mentioned below

**Runtime environment:**
 - OS: Ubuntu 20.04
 - Is this your local computer or a cloud host?  Google Colab
 - GPU: Tesla T4, 15GB

**Additional context**
I tried to install the module by my own but it just generate the log and ends

Error before test:
![6450294c162deb981ebdde34f12e27ac](https://user-images.githubusercontent.com/45272190/232327502-b21fd40a-d810-4868-b2e8-e9afd70dda1d.png)

Error after test:
![af9996ad20645b878e84221b0ef84430](https://user-images.githubusercontent.com/45272190/232327512-4682d678-3617-445e-812c-380e0fc61b05.png)

Log:
`04/16/2023 04:42:41 PM  Seed: 13276527
04/16/2023 04:42:41 PM Converting /content/drive/Shareddrives/Team Drive /everydreamlogs/ckpt/Sakimichan-ep20-gs05960.ckpt to Diffusers format
04/16/2023 04:42:41 PM Please manually convert the checkpoint to Diffusers format (one time setup), see readme.
`
Json:
`{
  "config": null,
  "amp": true,
  "batch_size": 3,
  "ckpt_every_n_minutes": null,
  "clip_grad_norm": null,
  "clip_skip": 1,
  "cond_dropout": 0.04,
  "data_root": "/content/drive/MyDrive/dreambooth/process",
  "disable_amp": false,
  "disable_textenc_training": false,
  "disable_unet_training": false,
  "disable_xformers": false,
  "flip_p": 0.0,
  "gpuid": 0,
  "gradient_checkpointing": true,
  "grad_accum": 1,
  "logdir": "/content/drive/Shareddrives/Team Drive /everydreamlogs",
  "log_step": 25,
  "lowvram": false,
  "lr": 1e-06,
  "lr_decay_steps": 0,
  "lr_scheduler": "constant",
  "lr_warmup_steps": 20,
  "max_epochs": 100,
  "notebook": false,
  "optimizer_config": "optimizer.json",
  "project_name": "Sakimichan",
  "resolution": 512,
  "resume_ckpt": "/content/drive/Shareddrives/Team Drive /everydreamlogs/ckpt/Sakimichan-ep20-gs05960.ckpt",
  "run_name": null,
  "sample_prompts": "sample_prompts.txt",
  "sample_steps": 300,
  "save_ckpt_dir": "/content/drive/Shareddrives/Team Drive /everydreamlogs/ckpt",
  "save_every_n_epochs": 5,
  "save_ckpts_from_n_epochs": 0,
  "save_full_precision": false,
  "save_optimizer": false,
  "scale_lr": false,
  "seed": -1,
  "shuffle_tags": false,
  "useadam8bit": false,
  "wandb": false,
  "validation_config": null,
  "write_schedule": false,
  "rated_dataset": false,
  "rated_dataset_target_dropout_percent": 50,
  "zero_frequency_noise_ratio": 0.05
}`

**Comment by meganano202** [comment]
I fixed it (thx to Guia34 on Disc)

Steps:
- Add `!pip install compel~=1.1.3` after the cell "Finish Install Dependencies into the new python"
- Run Everydream 2
- If dont works, run it enabling "resume"
- If the error is about "save_name":
   - Input in "Get A Base Model" the url/directory and model
   - Run "Get A Base Model"
   - Run Everydream 2

**Comment by victorchall** [comment]
Compel was added a day or two ago. If you are using docker it should be preinstalled on docker pull.  If you git pull you'll have to manually pip install new stuff (this also includes local/non-docker installs).  This was posted in #change-log in the discord with a warning to pip install compel.
