### ISSUE TITLE
Resuming with "findlast" does not take into account the project name

### ISSUE THREAD

**Issue by warnerchavescdp** [victorchall/EveryDream2trainer#146]
Hi Victor, great job with the tool! One issue with this scenario:

1. Create projectA, train it for X steps. Test it, do another run doing a resume ='findlast'
2. Want to switch it up temporarily, so you create projectB, do some work, etc.
3. Now you want to go back to resuming training for projectA, since the config file has the project name as projectA and resume as findlast, the assumption would be that it finds the last checkpoint for that project, however the tool actually finds the last checkpoint globally and it starts to train the checkpoint from projectB using a logs folder called projectA*** so it's even more confusing and hard to spot the issue. 

I assume the correct behavior for the user would be to find the last that belongs to that one particular project so that you can go back and forth between projects and use 'findlast' without having to go back and hardcode the last checkpoint into the config file. Cheers!

**Comment by victorchall** [comment]
Changing it to the way you describe would cause a significant amount of confusion from users at this point as they expect findlast to be an absolute timestamp search and not bound to project_name.  I understand the ask, but its pretty far in at this point to change the behavior and not be bombarded with questions and complaints if it were to change.

If you want to resume from a specific past run just copy and paste the directory with the model_index.json in your logs folder.

ex.  "resume_ckpt": "logs\myproj_20230331-003251\ckpts\last-myproj-ep199-gs15000"

**Comment by crackfoo** [comment]
It would be handy. I've found several times now, I used findlast and didn't realize I had a different project with a newer timestamp that it started the resume from.

Perhaps a different function then instead of mucking with the current findlast. Maybe a findproject, which will search the latest with whatever the project name is set as....

**Comment by victorchall** [comment]
Yeah "findlastofproject" would not interfere with current behavior, that's worth considering, I'll reopen, not sure if I'll have time for it soon but it may also be easy to add.

**Comment by vsemecky** [comment]
> Hi Victor, great job with the tool! One issue with this scenario:
> 
> 1. Create projectA, train it for X steps. Test it, do another run doing a resume ='findlast'
> 2. Want to switch it up temporarily, so you create projectB, do some work, etc.
> 3. Now you want to go back to resuming training for projectA, since the config file has the project name as projectA and resume as findlast, the assumption would be that it finds the last checkpoint for that project, however the tool actually finds the last checkpoint globally and it starts to train the checkpoint from projectB using a logs folder called projectA*** so it's even more confusing and hard to spot the issue.
> 
> I assume the correct behavior for the user would be to find the last that belongs to that one particular project so that you can go back and forth between projects and use 'findlast' without having to go back and hardcode the last checkpoint into the config file. Cheers!

This seems like expected behavior to me. I would also expect the last to be searched with respect to the project name.

**Comment by victorchall** [comment]
Not something I'll be adding, feel free to submit a PR for something like "findlast_matchingproject".
