### ISSUE TITLE
[ERROR] Error no 24 - too many open files

### ISSUE THREAD

**Issue by 5875johnsmith** [victorchall/EveryDream2trainer#165]
Using around 140K files for training - received many error 24 messages followed by training stop.  No logs were generated.
I'm hoping this is a simple issue, but I can't see any hints on github.

Am I trying to train too many?  I have run previously with 120k and that worked....

**Attach log and cfg** - NO LOG Generated

**Runtime environment (please complete the following information):**
 - OS: Win 10
 - local
 - 3090 24GB

**Additional context**

**Comment by victorchall** [comment]
If you can reproduce, can you simply copy the command window output from the point you start the training script?

![image](https://github.com/victorchall/EveryDream2trainer/assets/15839076/219f826d-bdc8-43b0-a939-105c595653fc)
You can click the top left icon, edit, select all, then click top left icon again, edit, copy.  The paste it here in reply.

I need a bit more context.  Not an error I've seen before.  

It may be worth just trying to reboot, maybe a process is stuck somewhere, only guess so far.

**Comment by victorchall** [comment]
Poking around more I feel this is likely something stuck and has a lot of file handles left open.  Maybe a prior run crashed but still running in the background.  I would try the reboot first and probably the fastest solution.

**Comment by aptecoSmith** [comment]
Thanks @victorchall - I resolved this by splitting the 140k into several smaller batches and using your excellent chaining functionality.
It might have resolved itself simply by the reboot - I know I have successfully trained on 120k.  I didn't try again as I considered a chaining workflow might be better in the long run in any case.
If I try this large number again, I will look out for this error and complete your instructions again.  I'm happy for this to close for for now.  Anyone hitting the same error can see this thread and that will hopefully be enough until a proper debug is possible.

**Comment by victorchall** [comment]
I use COCO2017 to test from time to time to test that loading works properly.  That is 125k total between train and val.  It uses bit of sys ram but shouldn't be holding onto file handles.  I think at least a few people have done 200k-300k.  If it consistently crashes let me know.   Would be helpful to know when, if it makes any progress on steps or crashes earlier than that.

It may also be something peculiar with how you organize, maybe if too many files are in a single folder, though I think coco2017 is 115k in the /train folder and it works fine on both linux and windows systems, however. Maybe at some point windows pukes?
