### ISSUE TITLE
[Feature]: integration as a submodule and support for Vlad diffusion

### ISSUE THREAD

**Issue by DirtyHamster** [victorchall/EveryDream2trainer#169]
I've been following your project for a little while, while looking into better training methodologies and techniques. After moving between A1111 and Vlad diffusion I found that neither suite had taken on the issue of model preservation within their training sections yet. After a brief chat with Vladmadic thinking that I might be able to load this as an extension he mentioned that it might be integrated it as a submodule to support it in all operations within the suite. Would you have any interest in helping facilitate this being added in like that? I'm thinking that it would be very useful to the community.

Thread that I have open on the Vlad diffusion page about this:
https://github.com/vladmandic/automatic/issues/961

Thanks in advance, I'm going to link back to this thread on that thread for him in order to put the two of you into contact with each other.

**Comment by victorchall** [comment]
I don't have any interest in making Everydream a submodule in another software suite.
