### ISSUE TITLE
Feature: Generate yaml file alongside SD ckpt

### ISSUE THREAD

**Issue by chris-aeviator** [victorchall/EveryDream2trainer#17]
It would be benefitial for SD2 models if the generation of the SD dumps would include the copying of the v2-inference.yaml config file. This way users could directly point inference toolkits like A1111 directly to the ED2Trainer folder. Right now I'm manually copying yaml files everytime I want to test a model coming out of ED2Trainer.

```
## A1111 needs the yaml file to be the same name as the ckpt file
cp last-2301_MYPROJ_fp16_adam_3rd_run_200-ep199-gs03000.yaml last-2301_MYPROJ_fp16_4th_512_single_instance_image_200-ep199-gs00200.yaml

## A1111 then can load the model directly from the ED2Trainer folder
  python launch.py --ckpt /finetuning/EveryDream2trainer/last-2301_MYPROJ_fp16_4th_512_single_instance_image_200-ep199-gs00200.ckpt
```

**Comment by UrbanLegendXV** [comment]
I second this motion and move to appeal.

**Comment by victorchall** [comment]
Not a bad idea... I should be able to do that.

**Comment by victorchall** [comment]
This has been pushed.  Should save the yaml renamed correctly for auto webui into the same folder as you save your ckpt (remember you can use "save_ckpt_dir": "somepath\\here\\there")

**Comment by victorchall** [comment]
![image](https://user-images.githubusercontent.com/15839076/213260620-8287dec9-3da3-4025-9cf3-578726a854f6.png)
