### ISSUE TITLE
Resolution For Training?

### ISSUE THREAD

**Issue by Travistyse** [victorchall/EveryDream2trainer#178]
I have a 3090 so I've got 24GB of VRAM and am wondering what resolution I should target? I'm pretty sure that I should use SD 1.5 still, right? But beyond that, I'm wanting to train on images that would benefit heavily from higher resolution for fidelity reasons. I've trained with EveryDream2Trainer in the past and am under the impression that it can automatically downscale images from higher resolutions but what's the highest resolution - with my graphics card - that I can train about 700 images with? 768x768 would be better than 512, 1024x1024 would be perfect. I'm guessing that neither are possible but am hoping?

**Comment by DirtyHamster** [comment]
From the readme file on data prep: Current recommendation is at least 1 megapixel (ex 1024x1024, 1100x900, 1300x800, etc). That being said, technology continues to advance rapidly. ED2 has no problem handling 4K images, so it's up to you to pick the appropriate trade-off with disk and network costs.

**Comment by Travistyse** [comment]
> From the readme file on data prep: Current recommendation is at least 1 megapixel (ex 1024x1024, 1100x900, 1300x800, etc). That being said, technology continues to advance rapidly. ED2 has no problem handling 4K images, so it's up to you to pick the appropriate trade-off with disk and network costs.

I uh.. I read the readme. I've used this tool in the past and have knowledge of the fact that it downsamples images. Basically, yeah the recommendation is to start higher and downsample and in the future higher resolution training methods might be available. But that was half a year ago that I was doing this last time and a lot has happened since then so I'm wondering if 24GB of VRAM might be enough to train 1024x1024 images and if that plays nicely with SD 1.5 if so because in the past iirc you wanted to train on the same resolution of images that the original model was trained with.

**Comment by Travistyse** [comment]
Answer is yes, but as expected you need to use SD 2.1 768
