### ISSUE TITLE
Resulting model can't be loaded with an inpainting pipeline due to shape mismatch

### ISSUE THREAD

**Issue by chris-aeviator** [victorchall/EveryDream2trainer#18]
when loading a fine tuned model with diffusers 

```
device = "cuda"
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    '/finetuning/EveryDream2trainer/logs/2301_MYPROJ_fp16_adam_nonema_20230116-155427/ckpts/2301_MYPROJ_fp16_adam_nonema-ep300-gs04201' ,
    revision="fp16",
    safety_checker=None,
    requires_safety_checker=False,
    feature_extractor=None,
    torch_dtype=torch.float16,
    use_auth_token=False
).to(device)

with autocast("cuda"):
    images = pipe(prompt="my amazing prompt", num_inference_steps=100, negative_prompt="negativity", image=init_image, mask_image=mask)["images"]
```

I get a size mismatch

```
incorrect configuration settings! The config of `pipeline.unet`: FrozenDict([...]) expects 4 but received `num_channels_latents`: 4 + `num_channels_mask`: 1 + `num_channels_masked_image`: 4 = 9. Please verify the config of `pipeline.unet` or your `mask_image` or `image` input.
```

So far I have been able to use inpainting with my previous models and understood the inpainting models are just "better" at inpainting (for instance I can always use inpainting inside A1111, no matter if my model is from ).

**Comment by victorchall** [comment]
There is a subtle difference on the inpainting models' channels.  I believe you can merge the model in CKPT format with the inpainting model in something like auto web ui to turn it into an inpainting model.  If you merge it at a ratio of 1% base inpainting and 99% your model it should assume the shape of inpainting but have almost entirely your weights.

Of course, the model needs to be available in inpainting format, which is true for I think SD1.5 and SD2.0.  So you can train SD1.5 or SD2.0-512base then merge those with SD1.5-inpainting or SD2.0-inpainting.

**Comment by chris-aeviator** [comment]
I'm able to load a CKPT file and use inpainting without any further merges in A1111 - the answer might be inside the conversion script - I'll try out what happens when I convert a CKPT back to diffusers format. NOTE: I'm interested into using diffusers over A1111.

**Comment by victorchall** [comment]
The trainer doesn't have native support for training the inpainting models as is.  I'm not sure its really a needed feature if you can just do the merge trick instead.
