### ISSUE TITLE
[feature] SmartFRZ support, for adaptive layer freezing 

### ISSUE THREAD

**Issue by bghira** [victorchall/EveryDream2trainer#182]
https://openreview.net/pdf?id=i9UlAr1T_xl

This is above my head but as I understand it, the loss value is used to adaptively freeze layers once they have converged, which ensures better network performance.

**Comment by victorchall** [comment]
Interesting.

You can now freeze text encoder layers based on a simple split.  I.e. "-6" to unfreeze only last 6 layers, which seems to be helping a lot with SD2.1

**Comment by victorchall** [comment]
Not planned.
