### ISSUE TITLE
[ERROR] NameError: name 'MODEL_URL' is not defined

### ISSUE THREAD

**Issue by meganano202** [victorchall/EveryDream2trainer#189]
**Runtime environment:**
- OS: Ubuntu 20.04
- Is this your local computer or a cloud host? Google Colab
- GPU Tesla T4, 15GB

**Additional context**
![image](https://github.com/victorchall/EveryDream2trainer/assets/45272190/13a581ed-88d7-43ed-9c8a-162794638b0a)

MODEL_URL is not defined anywhere so changing
`download_path = os.path.join(os.getcwd(), os.path.basename(MODEL_URL))`
to
`download_path = os.path.join(os.getcwd(), os.path.basename(MODEL_LOCATION))`
should fix that but I'm getting another error:

![image](https://github.com/victorchall/EveryDream2trainer/assets/45272190/b2c7bedf-bc0c-4092-92b9-29fc685345dc)

**Comment by meganano202** [comment]
Quick fix until fixed by admin:

1. Download the file using `!wget`
2. Move it to drive using `shutil.move`
3. Paste the directory in _Model Location_

```
import os
import shutil
from IPython.display import clear_output
from google.colab import drive
drive.mount('/content/drive')
URL = "https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/main/sd-v1-5-inpainting.ckpt" #@param{type: 'string'}
!wget $URL
name = os.path.basename(URL)
shutil.move('/content/' + name, '/content/drive/MyDrive/everydreamlogs/ckpt/'+ name)
clear_output()
print('DOWNLAODED AND MOVED!')
```
Paste this in a new cell between **Setup and Install** and **Get A Base Model**
![image](https://github.com/victorchall/EveryDream2trainer/assets/45272190/1f04b843-ab7e-42d5-885f-3fd5b56c28ea)

In _MODEL_LOCATION_ just paste the dir of the file that should be _/content/drive/MyDrive/everydreamlogs/ckpt/(filename)_

**Comment by victorchall** [comment]
This has been fixed, thanks for the heads up!
