### ISSUE TITLE
[ERROR] Run out RAM

### ISSUE THREAD

**Issue by meganano202** [victorchall/EveryDream2trainer#191]
```
{
  "config": null,
  "amp": true,
  "batch_size": 6,
  "ckpt_every_n_minutes": null,
  "clip_grad_norm": null,
  "clip_skip": 1,
  "cond_dropout": 0.04,
  "data_root": "/content/drive/Shareddrives/Team Drive /dreambooth/NeoArtCore",
  "disable_amp": false,
  "disable_textenc_training": false,
  "disable_unet_training": false,
  "disable_xformers": false,
  "flip_p": 0.0,
  "gpuid": 0,
  "gradient_checkpointing": true,
  "grad_accum": 1,
  "logdir": "/content/drive/Shareddrives/Team Drive /everydreamlogs",
  "log_step": 25,
  "lowvram": false,
  "lr": null,
  "lr_decay_steps": 0,
  "lr_scheduler": "constant",
  "lr_warmup_steps": null,
  "max_epochs": 100,
  "optimizer_config": "optimizer.json",
  "project_name": "NeoArtCore",
  "resolution": 512,
  "resume_ckpt": "panopstor/EveryDream",
  "run_name": null,
  "sample_prompts": "sample_prompts.txt",
  "sample_steps": 300,
  "save_ckpt_dir": "/content/drive/Shareddrives/Team Drive /everydreamlogs/ckpt",
  "save_every_n_epochs": 5,
  "save_ckpts_from_n_epochs": 0,
  "save_full_precision": false,
  "save_optimizer": true,
  "seed": -1,
  "shuffle_tags": false,
  "useadam8bit": false,
  "wandb": false,
  "validation_config": null,
  "write_schedule": false,
  "rated_dataset": false,
  "rated_dataset_target_dropout_percent": 50,
  "zero_frequency_noise_ratio": 0.01
}
```

**Runtime environment:**
- OS: Ubuntu 20.04
- Is this your local computer or a cloud host? Google Colab
- GPU Tesla T4, 15GB

**Additional context**
Some days ago I could train my old model without problems. But after the update the system run out RAM saving the ckpt file, but it saves the folder/uncompressed ckpt. The system has 12.7GB RAM

**Comment by victorchall** [comment]
If you have a lot of images it uses more system RAM as some meta data is stored in system RAM for each image (very small, but adds up).

You can try to reduce the size of your dataset to see if it helps, but the only other suggestion I have is to pay use the high mem instance.

**Comment by meganano202** [comment]
I keep testing reducing dataset and configs but anything changed. 

I tried to use other models but I get 2 types of errors:
- Repository dont have model_index (using HF directory)
- Wrong name repository (using Drive path)

Idk what changed in this updates that really increased the amunt of RAM usage. The normal RAM usage its 7.3 but saving ckpt goes to 12.3 and it makes it crash.

I paid 1 time for colab pro and I dont really recommend it, u run out units so fast

**Comment by victorchall** [comment]
The dataset size shouldnt matter unless its more than at least a few thousand.  How large is your dataset?  I'm assuming its fairly small, probably less than 1000?

Repository dont have model_index means its probably not a diffusers model.  It needs a model_index.json and folders for unet/vae.   This is unrelated to your memory error.

I don't know what wrong name repository means.  Need actual error, actual logs.

**Comment by meganano202** [comment]
In the previous model I used about 250 images and in this one I was going to use 300, but it started giving me the error.

So I reduced it by half but it didnt works.

I cant send the log file because it just generates the cfg.json file

**Comment by victorchall** [comment]
250 or 300 shouldn't be a problem, only if many many thousands or more.

I'm not sure if I can do much as the system RAM on free colab is extremely limited.  You can get high mem but you have to pay $10/mo at least to get pro I believe.
