### ISSUE TITLE
Does this work with 12GB

### ISSUE THREAD

**Issue by nanafy** [victorchall/EveryDream2trainer#2]
I am getting Cuda out of memory :(

**Comment by nanafy** [comment]
it does

**Comment by hashnag** [comment]
Do you mind sharing anything special you had to do to get it working?

**Comment by hashnag** [comment]
Do you mind sharing any extra steps you took to get it working?

**Comment by victorchall** [comment]
There's a --lowvram flag which will force some options that minimize VRAM use, but it is extremely tight to run 512 at batch size 1 on 12gb.
