### ISSUE TITLE
[BUG] Runpod Customize Deployment option ignores password environment variables

### ISSUE THREAD

**Issue by rvkwi** [victorchall/EveryDream2trainer#202]
Changing the password in runpods environment variables before deployment seems to not update it.
It will still remain with the default password and have that set in the environment variable in the container.

Just noticed and figured i post it. Happens on both main and nightly.

**To Reproduce**

- Select a container on runpod for everydream.
-  Click the `Customize Deployment` option.
- In the environment variables change the `JUPYTER_PASSWORD` to anything else but the default.

![edbg](https://github.com/victorchall/EveryDream2trainer/assets/122366820/2539d478-7ab3-42b8-ae55-77a59873be8b)

**Comment by victorchall** [comment]
Thanks for the report, I'll look into it.

**Comment by victorchall** [comment]
![image](https://github.com/victorchall/EveryDream2trainer/assets/15839076/03e146b3-b6da-4ea1-9ed5-1d15d37efec1)
I cannot reproduce, this worked just fine.
