### ISSUE TITLE
SDXL support

### ISSUE THREAD

**Issue by adhikjoshi** [victorchall/EveryDream2trainer#213]
Any plans for SDXL training support

**Comment by aiXander** [comment]
Very interested in this aswel!

**Comment by cohan8999** [comment]
Thirded!

**Comment by samsamm777** [comment]
+1

**Comment by official-elinas** [comment]
Agree, this would be a very beneficial feature over LoRAs.

**Comment by FoxMcCarther** [comment]
Would love to see this support sdxl1.0

**Comment by n0kovo** [comment]
This would be amazing, really.

**Comment by qudabear** [comment]
> To be honest, this library is the best for people who are familiar with deep learning. I think it is very important to support sdxl. I hope the author can update it, thank you!

SDXL is garbage and results from SD1.5 are better.
