### ISSUE TITLE
[ERROR] Something went wrong, attempting to save model 

### ISSUE THREAD

**Issue by miasik** [victorchall/EveryDream2trainer#215]
As I understand, I get the error when I play with
`"ckpt_every_n_minutes" or "save_every_n_epochs"

**Error:**

> 
> 
> Something went wrong, attempting to save model                                                                                                                                                                               | 1/18 [00:05<01:38,  5.82s/it, loss/step=0.18]
>  * Saving diffusers model to e:\SD\Trainings\FADplus\Logs\FADplus_20230719-193715/ckpts/errored-FADplus-ep10-gs00180
>  * Saving SD model to e:\SD\Trainings\FADplus\Saves\errored-FADplus-ep10-gs00180.ckpt
>  Saving optimizer state to e:\SD\Trainings\FADplus\Logs\FADplus_20230719-193715/ckpts/errored-FADplus-ep10-gs00180
> Model saved, re-raising exception and exiting.  Exception was: '>=' not supported between instances of 'int' and 'NoneType'
> Traceback (most recent call last):
>   File "e:\SD\EveryDream2trainer\train.py", line 978, in <module>
>     main(args)
>   File "e:\SD\EveryDream2trainer\train.py", line 903, in main
>     raise ex
>   File "e:\SD\EveryDream2trainer\train.py", line 849, in main
>     if epoch > 0 and epoch % args.save_every_n_epochs == 0 and step == 0 and epoch < args.max_epochs - 1 and epoch >= args.save_ckpts_from_n_epochs:
> TypeError: '>=' not supported between instances of 'int' and 'NoneType'
> Epochs:  13%|█████████████████▎                                                                                                                | 10/75 [48:11<5:13:15, 289.16s/it, img/s=0.0815, loss/log_step=0.144, lr_te=5e-7, lr_unet=1e-6, vram=12119/12288 MB gs:179]

- Windows 10
- Local
- 3060 12Gb

**Log:**
> 07/19/2023 07:37:15 PM [36m Batch size: 1, grad accum: 2, 'effective' batch size: 2[0m
07/19/2023 07:37:15 PM  Seed: 4233001662
07/19/2023 07:37:15 PM  unet attention_head_dim: 8
07/19/2023 07:37:15 PM Inferred yaml: v1-inference.yaml, attn: sd1, prediction_type: epsilon
07/19/2023 07:37:19 PM Enabled xformers
07/19/2023 07:37:30 PM * DLMA resolution 768, buckets: [[768, 768], [832, 704], [704, 832], [896, 640], [640, 896], [960, 576], [576, 960], [1024, 576], [576, 1024], [1152, 512], [512, 1152], [1280, 448], [448, 1280], [1408, 384], [384, 1408], [1472, 320], [320, 1472]]
07/19/2023 07:37:30 PM  Preloading images...
07/19/2023 07:37:30 PM  * [91mAspect ratio bucket ('default_batch', 576, 960) has only 1 images[0m. At batch size 1 this makes for an effective multiplier of 2.0, which may cause problems. Consider adding 1 or more images with aspect ratio 3:5, or reducing your batch_size.
07/19/2023 07:37:30 PM  * [91mAspect ratio bucket ('default_batch', 768, 768) has only 1 images[0m. At batch size 1 this makes for an effective multiplier of 2.0, which may cause problems. Consider adding 1 or more images with aspect ratio 1:1, or reducing your batch_size.
07/19/2023 07:37:30 PM  * DLMA initialized with 18 images.
07/19/2023 07:37:30 PM  ** Dataset 'train': 18 batches, num_images: 18, batch_size: 1
07/19/2023 07:37:30 PM [36m * text encoder optimizer: AdamW8bit (196 parameters) *[0m
07/19/2023 07:37:30 PM [36m    lr: 5e-07, betas: [0.9, 0.999], epsilon: 1e-08, weight_decay: 0.01 *[0m
07/19/2023 07:37:30 PM [36m * unet optimizer: AdamW8bit (686 parameters) *[0m
07/19/2023 07:37:30 PM [36m    lr: 1e-06, betas: [0.9, 0.999], epsilon: 1e-08, weight_decay: 0.01 *[0m
07/19/2023 07:37:30 PM  Grad scaler enabled: True (amp mode)
07/19/2023 07:37:30 PM  Pretraining GPU Memory: 6351 / 12288 MB
07/19/2023 07:37:30 PM  saving ckpts every 1000000000.0 minutes
07/19/2023 07:37:30 PM  saving ckpts every 10 epochs
07/19/2023 07:37:30 PM  unet device: cuda:0, precision: torch.float32, training: True
07/19/2023 07:37:30 PM  text_encoder device: cuda:0, precision: torch.float32, training: True
07/19/2023 07:37:30 PM  vae device: cuda:0, precision: torch.float16, training: False
07/19/2023 07:37:30 PM  scheduler: <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>
07/19/2023 07:37:30 PM  [32mProject name: [0m[92mFADplus[0m
07/19/2023 07:37:30 PM  [32mgrad_accum: [0m[92m2[0m
07/19/2023 07:37:30 PM  [32mbatch_size: [0m[92m1[0m
07/19/2023 07:37:30 PM  [32mepoch_len: [92m18[0m
07/19/2023 07:37:30 PM No plugins specified
07/19/2023 08:25:19 PM [93mSomething went wrong, attempting to save model[0m
07/19/2023 08:25:19 PM  * Saving diffusers model to e:\SD\Trainings\FADplus\Logs\FADplus_20230719-193715/ckpts/errored-FADplus-ep10-gs00180
07/19/2023 08:25:30 PM  * Saving SD model to e:\SD\Trainings\FADplus\Saves\errored-FADplus-ep10-gs00180.ckpt
07/19/2023 08:25:36 PM  Saving optimizer state to e:\SD\Trainings\FADplus\Logs\FADplus_20230719-193715/ckpts/errored-FADplus-ep10-gs00180
07/19/2023 08:25:41 PM [93mModel saved, re-raising exception and exiting.  Exception was:[0m[91m '>=' not supported between instances of 'int' and 'NoneType' [0m

**_cfg.json**
> {
  "config": "e:\\SD\\Trainings\\FADplus\\train.json",
  "batch_size": 1,
  "ckpt_every_n_minutes": null,
  "clip_grad_norm": null,
  "clip_skip": 0,
  "cond_dropout": 0.04,
  "data_root": "e:\\SD\\Training-data\\CurrentSession",
  "disable_amp": false,
  "disable_textenc_training": false,
  "disable_xformers": false,
  "flip_p": 0.0,
  "gpuid": 0,
  "gradient_checkpointing": true,
  "grad_accum": 2,
  "logdir": "e:\\SD\\Trainings\\FADplus\\Logs",
  "log_step": 18,
  "lowvram": false,
  "lr_decay_steps": 0,
  "lr_scheduler": "constant",
  "lr_warmup_steps": null,
  "max_epochs": 75,
  "notebook": false,
  "optimizer_config": "e:\\SD\\Trainings\\FADplus\\optimizer.json",
  "project_name": "FADplus",
  "resolution": 768,
  "resume_ckpt": "FAD",
  "run_name": null,
  "sample_prompts": "e:\\SD\\Trainings\\FADplus\\sample_prompts.json",
  "sample_steps": 18,
  "save_ckpt_dir": "e:\\SD\\Trainings\\FADplus\\Saves",
  "save_ckpts_from_n_epochs": null,
  "save_every_n_epochs": 10,
  "save_optimizer": true,
  "scale_lr": false,
  "seed": 4233001662,
  "shuffle_tags": true,
  "validation_config": "e:\\SD\\Trainings\\FADplus\\validation_default.json",
  "wandb": false,
  "write_schedule": true,
  "rated_dataset": false,
  "rated_dataset_target_dropout_percent": 50,
  "zero_frequency_noise_ratio": 0.02,
  "amp": true,
  "disable_unet_training": false,
  "lr": null,
  "no_prepend_last": false,
  "no_save_ckpt": false,
  "plugins": null,
  "save_full_precision": false,
  "useadam8bit": false
}

**Comment by luisgabrielroldan** [comment]
The `save_ckpts_from_n_epochs` must be a number. Use `0` instead of `null`.

**Comment by luisgabrielroldan** [comment]
Just realize there is a `setup_args` function.

Maybe adding this check?

```
if args.save_ckpts_from_n_epochs is None or args.save_ckpts_from_n_epochs < 1:
        args.save_ckpts_from_n_epochs = 1
```

**Comment by Macgyverops** [comment]
I get something similar.  ` Something went wrong, attempting to save model
 * Saving diffusers model to logs\redacted\ckpts\errored-redacted-ep00-gs00095
Traceback (most recent call last):
  File "redacted\EveryDream2trainer\train.py", line 1132, in main
    model_pred, target, loss = get_model_prediction_and_target(batch["image"], batch["tokens"], args.zero_frequency_noise_ratio, return_loss=True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "redacted\EveryDream2trainer\train.py", line 921, in get_model_prediction_and_target
    cuda_caption = tokens.to(text_encoder.device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. `

**Comment by victorchall** [comment]
Set `save_ckpts_from_n_epochs` to 0 indeed should solve the original issue.  The point is to declare from what epoch is the first that checkpoints are allowed to be saved when other rules are also met.  `null` doesn't make any sense, but `0` (always save when other requirements met) or perhaps something like `99999999` or `1e15` (effectively only save at end of training) might.  

@Macgyverops your issue looks completely unrelated.  It looks like a potential hardware problem as that shouldn't fail after 95 steps.  You can try the suggested setting of CUDA_LAUNCH_BLOCKING=1 to get a better error (in windows you can use `set CUDA_LAUNCH_BLOCKING=1` to set the ENV var and get a  better error in the command line prior to running `python train.py ...`   If you are still having problems please open a new issue as it is not related to the original post here.
