### ISSUE TITLE
[feature] define dataset metadata outside of dataset folders

### ISSUE THREAD

**Issue by mctb32** [victorchall/EveryDream2trainer#216]
First of all, thanks for making a great, feature rich tool! I would like to signal a need for a feature that could make working with projects and datasets easier.

It would be great if you could define the dataset metadata (multiply/batch_it/flip_p/etc.) inside the project definition (a separate json file perhaps?) instead of inside the actual data folders. I have multiple training folders with images that are shared between projects (mostly preservation datasets) and I have to modify files such as multiply.txt for every project/training session. When the training is done and I need to make a backup of the project settings, backing the project json files is not enough as again I need to make notes of all the metadata files inside each data subfolder. I know I would not need to do it if I made a copy of the entire dataset for each project, but it’s just not practical as many folders (mostly preservation) are shared between multiple projects/training iterations, and only the multiply.txt change for the most part. 

Or am I missing something, and there already is a way to decouple it in some way?

**Comment by victorchall** [comment]
Yes you can set `data_root` to point to a json file.

`--data_root x:/stuff/my_training_data.json`
