### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by killporter** [victorchall/EveryDream2trainer#222]
i'm trying to run the model in comfy, but i get missing {'first_stage_model.decoder.mid.attn_1.proj_out.bias', 'first_stage_model.decoder.mid.attn_1.k.weight', 'first_stage_model.decoder.mid.attn_1.proj_out.weight', 'first_stage_model.encoder.mid.attn_1.v.bias', 'first_stage_model.decoder.mid.attn_1.v.weight', 'first_stage_model.encoder.mid.attn_1.q.bias', 'first_stage_model.encoder.mid.attn_1.v.weight', 'first_stage_model.encoder.mid.attn_1.q.weight', 'first_stage_model.encoder.mid.attn_1.k.weight', 'first_stage_model.encoder.mid.attn_1.k.bias', 'first_stage_model.decoder.mid.attn_1.q.bias', 'first_stage_model.decoder.mid.attn_1.v.bias', 'first_stage_model.decoder.mid.attn_1.k.bias', 'first_stage_model.decoder.mid.attn_1.q.weight', 'first_stage_model.encoder.mid.attn_1.proj_out.weight', 'first_stage_model.encoder.mid.attn_1.proj_out.bias'}
missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
left over keys: dict_keys(['first_stage_model.encoder.mid.attn_1.to_q.weight', 'first_stage_model.encoder.mid.attn_1.to_q.bias', 'first_stage_model.encoder.mid.attn_1.to_k.weight', 'first_stage_model.encoder.mid.attn_1.to_k.bias', 'first_stage_model.encoder.mid.attn_1.to_v.weight', 'first_stage_model.encoder.mid.attn_1.to_v.bias', 'first_stage_model.encoder.mid.attn_1.to_out.0.weight', 'first_stage_model.encoder.mid.attn_1.to_out.0.bias', 'first_stage_model.decoder.mid.attn_1.to_q.weight', 'first_stage_model.decoder.mid.attn_1.to_q.bias', 'first_stage_model.decoder.mid.attn_1.to_k.weight', 'first_stage_model.decoder.mid.attn_1.to_k.bias', 'first_stage_model.decoder.mid.attn_1.to_v.weight', 'first_stage_model.decoder.mid.attn_1.to_v.bias', 'first_stage_model.decoder.mid.attn_1.to_out.0.weight', 'first_stage_model.decoder.mid.attn_1.to_out.0.bias', 'cond_stage_model.transformer.text_model.embeddings.position_ids'])
loaded straight to GPU

![ComfyUI_00334_](https://github.com/victorchall/EveryDream2trainer/assets/128866205/da168635-bf47-4151-b45d-4ef39e80fbf7)

it was trained with the ed2 repo

the problem happens in automatics as well, it generates the image well, but in the end, it just outputs a noise paste

**Comment by victorchall** [comment]
ED2 now only produces safetensors files and I think this has resolved issues loading files into auto1111.
