### ISSUE TITLE
Multiple GPUs Parallel Trainning.

### ISSUE THREAD

**Issue by Zheng-Chong** [victorchall/EveryDream2trainer#223]
Maybe I missed something, but from the code I saw that it only support a single GPU training now. Is there a plan to support multiple GPUs parallel.

**Comment by AILTY** [comment]
+1

**Comment by bghira** [comment]
i've added support for multi-GPU SD 1.x/2.x and SDXL training in [SimpleTuner](https://github.com/bghira/SimpleTuner), it's not trivial to add for trainers that support aspect bucketing. It's also very expensive to work on, since it requires access to the hardware.

**Comment by zhangvia** [comment]
i think this repo is not designed for multi-gpu traning. I modified this repo using the accelerate library to support multi-GPU training, but I found that the GPU memory consumption became very unstable. Moreover, the memory consumption on a single card is much higher than when training with a single GPU (under the same parameter settings)

**Comment by victorchall** [comment]
Not planned.
