### ISSUE TITLE
[BUG]about multi-gpu training

### ISSUE THREAD

**Issue by zhangvia** [victorchall/EveryDream2trainer#244]
I modified this repo using the accelerate library to support multi-GPU training, but I found that the GPU memory consumption became very unstable. Moreover, the memory consumption on a single card is much higher than when training with a single GPU (under the same parameter settings)

Do you have any suggestions?

**Comment by victorchall** [comment]
I'm wary of accelerate as it is a pretty thin layer on top of Pytorch's DDP, etc. and rips out some control.   I had it in ED2 prior to releasing it on github and ended up removing it because I didn't like it.

**Comment by zhangvia** [comment]
> I'm wary of accelerate as it is a pretty thin layer on top of Pytorch's DDP, etc. and rips out some control out of the engineer's hands and makes it difficult to get the control back, ex. declaring your own grad scaler. I had it in ED2 prior to releasing it on github and ended up removing it because I didn't like it.

uhh，i think accelerate can declare an custom grad scaler. i 've applied the accelerate to your scripts, and the gpu vram will be stable after a couple of training steps. but there is another problem. when i use 8 gpu ,and a lot of image about several hundred thousand image, the training process will be killed without any error message. i think the problem probably is the cpu ram. could you tell me what did you do in data preparation?

**Comment by victorchall** [comment]
Not planned.
