### ISSUE TITLE
"RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same"

### ISSUE THREAD

**Issue by NolmIgnis** [victorchall/EveryDream2trainer#252]
**Attach log and cfg**
[IgnisTest-20240301-101325.log](https://github.com/victorchall/EveryDream2trainer/files/14458929/IgnisTest-20240301-101325.log)
[IgnisTest-20240301-101325_main.json](https://github.com/victorchall/EveryDream2trainer/files/14458935/IgnisTest-20240301-101325_main.json)
[IgnisTest-20240301-101325_opt.json](https://github.com/victorchall/EveryDream2trainer/files/14458937/IgnisTest-20240301-101325_opt.json). 

**Runtime environment (please complete the following information):**
 - OS: Windows 11

 - Local computer
 - GPU [4070ti 64GB]

**Additional context**
Hi everyone !

I'm really struggling here, I try to launch EveryDream2 for the first time, pretty sure my whole setup is good but this error message keep occurs.

"RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same"

I have verify most of the possibility, including the [conv.py](https://conv.py/), the vae.py and the [train.py](https://train.py/) and it look like it doesn't come frome here. I had modified the train.json file but nothing too fancy.

I hope I can get some help from you, tell me if you had this kind of problem or if you need more informations.

**Comment by victorchall** [comment]
I would delete your venv folder and run windows_setup.cmd again to recreate it.  I'm not sure why you'd ever get that error.

**Comment by victorchall** [comment]
Closing as stale.
