### ISSUE TITLE
Feature request: Save checkpoint on exit

### ISSUE THREAD

**Issue by Jdbaii** [victorchall/EveryDream2trainer#254]
This would be a very useful feature for being able to pause the training any time, and resume from the exact point it left off.
I run it on my main desktop so sometimes I need to pause training to do other things.
For now I have set it to create a checkpoint every 2 hours, but it quickly takes up a lot of space on my drive since older checkpoints are not deleted automatically, and means I could still lose up to 2 hours of progress every time I pause the training.
Is this something that would be possible / easy to implement?

**Comment by victorchall** [comment]
This is already a feature.  Ctrl-C to stop training will trigger a save. /logs/[project-timestamp]/ckpts/interrupted[...]/

You can use resume_ckpt "findlast" and it will automatically find it and resume. Keep in mind it doesn't track epochs done so its not quite precise continuation, but you can adjust the max_epochs down for how much was completed when you resume with the "findlast" trick.

**Comment by victorchall** [comment]
I think this solves your issue. Use ctrl-c one time and let it save the interrupted checkpoint, from which you can resume with "findlast".
