### ISSUE TITLE
Colab error after running the first block[BUG]

### ISSUE THREAD

**Issue by aripsam** [victorchall/EveryDream2trainer#255]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2ab3960e1e9a> in <cell line: 96>()
     94 Python_version = get_ipython().getoutput('python --version')
     95 import torch
---> 96 import torchvision
     97 import xformers
     98 

1 frames
/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py in <module>
      2 
      3 import torch
----> 4 import torch._custom_ops
      5 import torch.library
      6 

ModuleNotFoundError: No module named 'torch._custom_ops'

I tried installing torchvision again but no luck.

**Comment by victorchall** [comment]
No one is actively maintaining the Colab notebook.  
The 12.5GB of system/cpu memory given causes issues anyway, which leads me to having to recommend the paid version, but at that point it's cheaper to rent on vast or runpod and get a superior GPU (i.e. 3090) for less.
If someone wants to volunteer to work through the issue I imagine it needs the requirements updated and some testing to figure out, but it's not something I use myself and am unlikely to work on.

**Comment by aripsam** [comment]
I actually was able to make it work a couple of months ago with the free tier. All I did was save the checkpoint only at the end of the 100th step. But yeah, seems like there's some issues with the requirements.
