### ISSUE TITLE
[ERROR]: finetuned model doesn't work with diffusers and comfyui

### ISSUE THREAD

**Issue by crapthings** [victorchall/EveryDream2trainer#257]
this error is from comfyui

Missing VAE keys ['encoder.mid.attn_1.q.weight', 'encoder.mid.attn_1.q.bias', 'encoder.mid.attn_1.k.weight', 'encoder.mid.attn_1.k.bias', 'encoder.mid.attn_1.v.weight', 'encoder.mid.attn_1.v.bias', 'encoder.mid.attn_1.proj_out.weight', 'encoder.mid.attn_1.proj_out.bias', 'decoder.mid.attn_1.q.weight', 'decoder.mid.attn_1.q.bias', 'decoder.mid.attn_1.k.weight', 'decoder.mid.attn_1.k.bias', 'decoder.mid.attn_1.v.weight', 'decoder.mid.attn_1.v.bias', 'decoder.mid.attn_1.proj_out.weight', 'decoder.mid.attn_1.proj_out.bias']

https://github.com/huggingface/diffusers/issues/8320

**Comment by victorchall** [comment]
I responded on the issue.  HF has ran from supporting any sort of conversion scripts, and its a constant problem.

**Comment by victorchall** [comment]
https://github.com/victorchall/EveryDream2trainer/blob/main/utils/backdate_vae_keys.py

For the time being you can run this script to change the keys on the .safetensors file.  It's already in your repo.

`python utils/backdate_vae_keys.py --filea myfile.safetensors --backdate`

Sometimes you have to do that, sometimes not.  Depends on the application.  I don't think Auto1111 cares for instance.
