### ISSUE TITLE
Discord url is outdated

### ISSUE THREAD

**Issue by popovidis** [victorchall/EveryDream2trainer#258]

**Comment by victorchall** [comment]
https://discord.com/invite/uheqxU6sXN

That's the link at the top of the readme with the Discord icon.  I clicked and it still worked for me?

**Comment by popovidis** [comment]
> https://discord.com/invite/uheqxU6sXN
> 
> That's the link at the top of the readme with the Discord icon. I clicked and it still worked for me?

![image](https://github.com/victorchall/EveryDream2trainer/assets/120704725/149a7729-0ab3-4908-8355-fdd48661acc8)

**Comment by victorchall** [comment]
I generated a fresh link and changed the readme.

https://discord.gg/nQaxwrPT

Hopefully will work for you, it is supposed to be permanent.

**Comment by victorchall** [comment]
If you have any more issues, please let me know, closing for now.
