### ISSUE TITLE
[BUG] RunPod Jupyter is Empty

### ISSUE THREAD

**Issue by popovidis** [victorchall/EveryDream2trainer#260]
I followed the tutorial in the video and got no files in the Jupyter.

![image](https://github.com/victorchall/EveryDream2trainer/assets/120704725/96f782f6-e44e-4726-ab08-99a0b19f4c9c)

**Comment by victorchall** [comment]
There's an issue with using Secure Cloud obliterating the repo from the docker image.  Community Cloud works fine.

You should be able to git clone the repo and be g2g.

**Comment by popovidis** [comment]
> There's an issue with using Secure Cloud obliterating the repo from the docker image. Community Cloud works fine.
> 
> You should be able to git clone the repo and be g2g.

I tried to git clone it to a desktop image and it had cuda errors. But when I used the correct image it would obliterate as you would say it so I would have to git clone it again and pip install by hand, which works but annoying.

**Comment by victorchall** [comment]
Yes, you can git clone the repo after you launch, pip install -r requirements.txt and it should work.

The docker image still ensures you have a working image.

I don't use runpod myself and don't really have time to fix it, I think the workspace needs to be mounted differently.  Something with how runpod secure works doesn't like it.

**Comment by Enixile** [comment]
This issue sounds similar to what I experience when using the docker-compose.yml, which includes a volume mapping for "/workspace/EveryDream2trainer". The dockerfile does a git clone of the repository to that directory successfully, but then the empty host volume is mounted in its place. I couldn't find a solution that I was confident wouldn't break something. I worked around it by specifying volumes for subdirectories such as input and logs instead, which are initially empty anyway.

**Comment by kodxana** [comment]
@victorchall Madiator2011 from here so I made custom template that should work out of box.
Template link: https://runpod.io/console/deploy?template=cpl3xoknjz&ref=vfker49t
And my git repo so people can submit RunPod template questions: https://github.com/kodxana/madiator-docker-runpod/tree/main/official-templates/better-everydream2

@popovidis fell free to give it a go :)

**Comment by victorchall** [comment]
Thanks. I've updated the link in the documents here:

https://github.com/victorchall/EveryDream2trainer/blob/main/doc/CLOUD_SETUP.md
