### ISSUE TITLE
Runpod does NOT work [ERROR]

### ISSUE THREAD

**Issue by qudabear** [victorchall/EveryDream2trainer#263]
Runpod Everydream2 trainer does not work and has not worked for months...

**Comment by qudabear** [comment]
Edit: it was a Runpod error with secure cloud (still not fixed). Only works on community cloud.

**Comment by victorchall** [comment]
If you need help you're going to need to provide sufficient information so I can begin to troubleshoot.  Screenshots, logs, even a basic description of the problem to start?

I don't actually use runpod myself, and the template was created by another user.
