### ISSUE TITLE
I cant get it to run on 3060 12GB :(

### ISSUE THREAD

**Issue by nanafy** [victorchall/EveryDream2trainer#3]
Anything I should be doing differently to get it to run? Able to run SD_extension and shivam repo.

python train.py --resume_ckpt "sd_v1-5_vae" --data_root "input"  --max_epochs 10  --lr_scheduler constant  --project_name testo --batch_size 1  --sample_steps 20 --lr 1e-6  --resolution 512  --clip_grad_norm 1  --ckpt_every_n_minutes 30  --useadam8bit --amp --mixed_precision fp16

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.26 GiB already allocated; 0 bytes free; 11.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Epochs:   0%|                                                                                                                                                                        | 0/10 [00:56<?, ?it/s, vram=4867/12288 MB gs:0]
Steps:   1%|█▎

Really looking forward to using your repo, it looks awesome. Thanks for all your hard work!

**Comment by nanafy** [comment]
Perhaps adding an option to enable/disable EMA and disable/enable caching latents we can hit the last little hump!

**Comment by victorchall** [comment]
For now, FP16 reduced precision is not supported until I can ensure it runs well and there are sane defaults for hyperparameters for it.  FP16 will be required to get it to run on 12GB or 16GB (i.e. Colab/T4) cards.  I'll announce on the discord when this is ready.

**Comment by nanafy** [comment]
Thanks Victor, so close! haha I was only shy 20mb. Looking forward to your update!!

**Comment by victorchall** [comment]
12GB is now supported.  See https://github.com/victorchall/EveryDream2trainer/blob/main/doc/LOWVRAM.md for details on what settings to use @nanafy

**Comment by nanafy** [comment]
Hi Victor. Thank you so much for notifying me. I am already downloading it. Excited to check it out. Appreciate it!
