### ISSUE TITLE
Saving every N epochs worked once but has not worked for me since.

### ISSUE THREAD

**Issue by EmmaWebGH** [victorchall/EveryDream2trainer#40]
Checkpoint saving worked the very first time I ran this, but then doesn't occur since.
Not doing anything complex-  only 3 images in "input" and the following args:

```
python train.py --resume_ckpt "sd_v1-5_vae" ^
--max_epochs 500 ^
--resolution 512 ^
--data_root "input" ^
--lr_scheduler constant ^
--project_name mfrkr_sd15 ^
--batch_size 3 ^
--sample_steps 25 ^
--lr 1e-6 ^
--shuffle_tags ^
--save_every_n_epochs 25 ^
--amp ^
--useadam8bit ^
--ed1_mode

```
It makes the sample every 25 OK, but doesn't save a checkpoint at epoch 25. Only at the end.

```
Epochs: 100%|██| 500/500 [15:15<00:00,  9.02s/it, img/s=5.14, loss/log_step=0.138, lr=1e-6, vram=20075/24564 MB gs:499] * Saving diffusers model to logs\mfrkr_sd15_20230131-154030/ckpts/last-mfrkr_sd15-ep499-gs00500
 * Saving SD model to .\last-mfrgx_sd15-ep499-gs00500.ckpt

```
And that's the only time the console prints anything about a checkpoint save.
What am I doing wrong please? :)

**Comment by victorchall** [comment]
Make sure you are up to date on the repo.    Use `git pull`.  

How many images do you have? It's possible if you only have 1 step per epoch it may not trigger.  

500 epochs is an awful lot.

ED1 mode is deprecated and no longer does anything.

**Comment by EmmaWebGH** [comment]
It's only 3 images (but I can see from the samples it's working). As I get the hang of it I'll get a better idea of how many steps/epochs, but for now I was going to overtrain but step back x-number of ckpts to find a usable one.
I will update and see if that helps.
Didn't realize ED1 was deprecated, I was copying and pasting from examples! :)
Came here after a reddit post recommended this, and it seems to get good results, so I also wanted to say, you should post about this repo more on places like that. For example, my first try was training for style, not a person, and it really seemed to do well... and there are a lot of people on Reddit wondering how to train style (as all the examples are "insert your own face").
Cheers friend

**Comment by nawnie** [comment]
You should join the discord as there is plenty of training information and people that can help

**Comment by victorchall** [comment]
I'll check but I believe things may break when your epoch is only 1 step long.  I recommend adding more data for a large number of reasons.

**Comment by victorchall** [comment]
Yeah, I checked, it won't save if you only have 1 step per epoch (i.e. your batch_size is equal or larger than the number of images you're using for training).  Add more data.  I don't recommend trying to train on so few images.
