### ISSUE TITLE
Sample generated images are always identical at every training step

### ISSUE THREAD

**Issue by Angtrim** [victorchall/EveryDream2trainer#44]
While I'm training the model, the sample generated images are always identical (at a pixel level) at every step.
It seems that they are generated by using the same weights instead from the updated model.

**Comment by victorchall** [comment]
Need to see your entire log and cfg file.  .log and cfg.json from your log folder.  Maybe you disabled training.

**Comment by Angtrim** [comment]
Thanks for the quick answer.
Please find attached the logs files.

Anyway, yes, it seems it's not training.
The step loss does not seem to change or get better.

[loggerphototest-20230202-104443.log](https://github.com/victorchall/EveryDream2trainer/files/10569491/loggerphototest-20230202-104443.log)

[loggerphototest-20230202-104443_cfg.txt](https://github.com/victorchall/EveryDream2trainer/files/10569497/loggerphototest-20230202-104443_cfg.txt)

**Comment by Angtrim** [comment]
I'm using the colab version btw

**Comment by victorchall** [comment]
Your sample prompts are ['photo of a portrait of a business man', 'photo of a portrait of a surfer']

What are the captions on your images?  If they are not "business man" or "surfer" its probably not going to do anything.

**Comment by victorchall** [comment]
Going to assume nawnie fixed a bug.   Let us know if it breaks again.
