### ISSUE TITLE
Runpod issue

### ISSUE THREAD

**Issue by atabv** [victorchall/EveryDream2trainer#47]
You gotta take a look at your runpod .ipynb file. It won't run with the 2.1.10 docker you specified. 
There are couple of issues with it, but your docs are incomplete (firstly your hf_downloader downloads at the wrong place, then it is missing config files, etc.)
Please fix it.

**Comment by victorchall** [comment]
@qslug

**Comment by jmattthew** [comment]
I wasn't able to run this on Runpod following the instructions from "everydream-v2-trainer-runpod.ipynb"

Like everdream1, the instructions say to put training images in the "input" directory.  However, unlike everydream1, that directory wasn't created.  I created it manually.

No errors were reported, but when running the train cell, the output was
```
  0%|          | 0/120 [00:00<?, ?it/s]
  0%|          | 0/44 [00:00<?, ?it/s]
  0%|          | 0/44 [00:00<?, ?it/s]
  0%|          | 0/44 [00:00<?, ?it/s]
  0%|          | 0/44 [00:00<?, ?it/s]
  0%|          | 0/44 [00:00<?, ?it/s]
  ...etc.
```
120 was my max_epochs.  I don't know what the 44 refers to

**Comment by victorchall** [comment]
Qslug has been regularly updating the runpod, you may try again.
