### ISSUE TITLE
Holding `CTRL+ALT+PAGEUP` does not kick off sampling

### ISSUE THREAD

**Issue by hopto-dot** [victorchall/EveryDream2trainer#54]
As the title says, holding `CTRL+ALT+PAGEUP` does not kick off sampling, even after pressing this shortcut for over 30 seconds.

Just to make it evidently clear I'm pressing (and holding) these buttons:
https://i.imgur.com/3ka60uF.png

I am running EveryDream2trainer on Windows 10 in the command prompt.

**Comment by victorchall** [comment]
This was removed because it causes a problems with runpod/linux/colab.  Having broad system support is more important than the trivial feature of instant sampling.

I updated the docs to remove the mention.

**Comment by hopto-dot** [comment]
Might want to remove the mention of that from [doc/TRAINING.md](https://github.com/victorchall/EveryDream2trainer/blob/main/doc/TWEAKING.md) in that case.

**Comment by victorchall** [comment]
> I updated the docs to remove the mention.

I did as of writing the above comment.

https://github.com/victorchall/EveryDream2trainer/commit/5be15f0f16e5ccbe85ae368a833c52218a121aec
