### ISSUE TITLE
Error in model conversion on colab for SD 2.1

### ISSUE THREAD

**Issue by MNoichl** [victorchall/EveryDream2trainer#55]
I think there is a small error in the colab-notebook. If you try to convert the 2.1 model, by default it's still using the 'epsilon' prediction type, which will result in pretty deep-fried results (see below).

😄 Thank you for the great repository! I'm having a lot of fun with it! 😄 

```
!python utils/convert_original_stable_diffusion_to_diffusers.py --scheduler_type ddim  \
--original_config_file {inference_yaml} \
--image_size {img_size} \
--checkpoint_path {base_path} \
--prediction_type epsilon \ <-- This should change.
--upcast_attn False \
--dump_path {save_name}
```

Here's a sample of the results... 💀 
![gs00299-0-oil painting of a burning skull](https://user-images.githubusercontent.com/34612138/217672403-f2a07be1-6e0b-4cf3-b34a-45d6f23d0806.jpg)

**Comment by victorchall** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15839076/217697554-7b8cc5f4-1583-4a93-9731-9b590f7f3294.png)
