### ISSUE TITLE
suggestion:  add "--dont_save_until_x_epochs"  param

### ISSUE THREAD

**Issue by jmattthew** [victorchall/EveryDream2trainer#62]
Sometimes you already know when you start training that the model won't be any good until many epochs have passed, so there's no point in saving the model until training has passed that point.  But after those n epochs, you don't already know when overfitting will occur.  So you want the "--save_every_n_epochs" param to be low.  But if it's low, you end up with many unneeded saved models, and you have limited storage.  

Adding a "--dont_save_until_x_epochs" param would fix that by not saving any of the first x-1 epochs, but saving x and afterwards saving every n epochs.

**Comment by victorchall** [comment]
I may add something like "save_last_n_epochs" instead, there's some discussion about it on the discord.

**Comment by victorchall** [comment]
"save_ckpts_from_n_epochs" has been added.  Say, if your max_epochs is 20 and save_every_n_epochs is 5, and save_ckpts_from_n_epochs is 11, it will not save at epoch 5 or 10 and will save at epochs 15 and 20 only.
