### ISSUE TITLE
Let's Work Together

### ISSUE THREAD

**Issue by d8ahazard** [victorchall/EveryDream2trainer#68]
Hey there! Developer of the dreambooth extension for Auto1111 (and soon to be a stand-alone application) here.

I was recently made aware of some of enhancements you've added to the Dreambooth training process, and would cordially like to invite you to a discussion regarding a collaboration between you, myself, and some of the other prominent developers working on Dreambooth/SD training, with an end goal of coming together to create one new uniform training method with all the bells and whistles.

If you're interested, I've got a discord over here where I'll be inviting some of the other devs to come and chat. It'd be awesome to talk with you and discuss how we can work together. ;)

https://discord.gg/q8dtpfRD5w

**Comment by victorchall** [comment]
Thanks, I will consider.
