### ISSUE TITLE
windows_setup.cmd fails with fatal error 

### ISSUE THREAD

**Issue by syberphunk** [victorchall/EveryDream2trainer#69]
Installed python 3.10, ran windows_setup.cmd, downloaded requirements, ended with this:

` *** Applying bitsandbytes patch for windows ***
 *** Already patched!
 *************************************************************
 *** bitsandbytes windows patch applied, attempting import ***
Somethnig went wrong trying to patch bitsandbytes, aborting
make sure your venv is activated and try again
or if activated try:
    pip install bitsandbytes==0.35.0
Traceback (most recent call last):
  File "C:\repo\EveryDream2trainer\utils\patch_bnb.py", line 122, in main
    import bitsandbytes
  File "C:\repo\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\repo\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 4, in <module>
    import torch
  File "C:\repo\EveryDream2trainer\venv\lib\site-packages\torch\__init__.py", line 219, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"`

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\repo\EveryDream2trainer\utils\patch_bnb.py", line 133, in <module>
    main()
  File "C:\repo\EveryDream2trainer\utils\patch_bnb.py", line 125, in main
    error()
  File "C:\repo\EveryDream2trainer\utils\patch_bnb.py", line 94, in error
    raise RuntimeError("** FATAL ERROR: unable to patch bitsandbytes for Windows env")
RuntimeError: ** FATAL ERROR: unable to patch bitsandbytes for Windows env
 downloaded: v2-inference-v.yaml
 downloaded: v2-inference.yaml
 downloaded: v1-inference.yaml
SD1.x and SD2.x yamls downloaded

(venv) C:\repo\EveryDream2trainer>python --version
Python 3.10.10`

**Comment by victorchall** [comment]
Close your command window.
Delete venv folder.
Open a new command window and run the windows_setup.cmd again.

**Comment by syberphunk** [comment]
*** Applying bitsandbytes patch for windows ***
 *************************************************************
 *** bitsandbytes windows patch applied, attempting import ***
CUDA SETUP: Loading binary C:\repo\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 *** bitsandbytes patch succeeded, everything looks good!  ***
 downloaded: v2-inference-v.yaml
 downloaded: v2-inference.yaml
 downloaded: v1-inference.yaml
SD1.x and SD2.x yamls downloaded

Success. Thanks.
