### ISSUE TITLE
Validation no output

### ISSUE THREAD

**Issue by salmjak** [victorchall/EveryDream2trainer#71]
Hi!
Using the default validation config on google colab produces no output.
When an epoch finishes it will validate for a few steps but there is no loss/val output in the console.

**Comment by victorchall** [comment]
It logs it into tensorboard, there's an issue now with wandb which is going to be more useful for people running remote runtimes, you could potentially download the events log file and load it locally on tensorboard in the short term

**Comment by salmjak** [comment]
Thank you!
I tried using wandb but didnt understand how to set it up properly since no loss-values were showing.
I realised that I can use tensorboard locally while using Google Drive for desktop.
