### ISSUE TITLE
Model not training on runpod and colab

### ISSUE THREAD

**Issue by xcreateadmin** [victorchall/EveryDream2trainer#74]
Runpod and Google Colab training is not working for the past few days.

I am not getting any errors but after training when I test the model it seems like it's not trained at all. 
I didn't get my style/ person /object even by using caption tokens. 
With the same setting and same data, it used to work on Colab and run pod. 
I am using default settings only.

For eg. Earlier prompt "doctor in rdanimestyle" is used to give a doctored image in the trained style. 
Earlier even "doctor" prompts were used to give outputs in a trained style. 
Now the same prompts are just given to a normal outputs.

I used all naming methods, like 

- 0001.jpg , 0001.txt 
- rdanime boy_.jpg , rdanime boy_.txt 
- using caption as the image name etc. 

When testing using runpod and colab test section I am pretty sure the image results are coming from base SD 1.5v model only not the trained model. 

I also downloaded last-....ckpt and tested it with other colab still results are like base mode. So I think the issue is with training, not the testing code.

Would really appreciate your help on this.

**Comment by victorchall** [comment]
I tested colab at least and seems fine, I believe quslug is looking into issues for runpod and xformers being weird again.  Ongoing discussions on the discord.
