### ISSUE TITLE
Use of "_" and "," to delineate different prompt areas

### ISSUE THREAD

**Issue by ventolin42** [victorchall/EveryDream2trainer#76]
Hi, i am just preparing my dataset for use with Everydream, however i found some issues due to the unfortunate use of common characters like "," and "_" to delineate different sections of the training prompt.

For Tag shuffling "," is used to separate the first chunk (caption that is not shuffled) from all other chunks (tags that are shuffled). However this means that the caption can not contain a "," as this would declare everything after the "," to be tags and include it in shuffling.

A similar issue is the use of the underscore  to separate the training promt from everything that is ignored at the end of the prompt. This means the tags can not contain a underscore as anything behind the first "_" would be ignored by the trainer. Unfortionately underscores are common in original booru-tags so those can not be used for training with everydream (without replacement of all underscores by spaces).

A suggestion would be to use more uncommon characters or escape-sequences to delineate the different sections of the training prompt (the "training section", the "tag section" and the "ignore section"). As an example you could use two points ".." to separate the caption section from the tags section and two underscores "__" to separate the tag section from the ignore section. Then the two issues mentioned above would not exist.

**Comment by victorchall** [comment]
Underscore has no special meaning if it is in the .txt instead.  There's a script in the Every Dream tools repo that will push the filename captions into .txt for you, then you can modify from there.  There's also a very simple GUI editor to edit the .txt files after that.

There's no doc for this but its very easy to use:
https://github.com/victorchall/EveryDream/blob/main/scripts/createtxtfromfilename.py

Simple gui mstevenson made:
https://github.com/victorchall/EveryDream/blob/main/doc/CAPTION_GUI.md

For tag shuffling, there's a more complex yaml option with more control but there's no easy way to edit or create them in bulk.  Some sort of more "interesting" way to perform data augmentation has been floating around in my head and in the discord community, but it's not entirely obvious what the best approach is.  Whatever it is, some meaingful edit

For now I think the shuffle tags options with csv is more just there for people doing booru tagged data, which is just a giant jumble of tags in CSV format.  I generally do not use it myself.
