### ISSUE TITLE
Training stops when generating samples

### ISSUE THREAD

**Issue by what3vr** [victorchall/EveryDream2trainer#79]
Everything seems to work fine up until the first sample generation and then it stops with this:

D:\EveryDream2trainer\venv\lib\site-packages\torch\utils\checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Something went wrong, attempting to save model
 * Saving diffusers model to logs\Original_Inked_Artv15_20230218-184037/ckpts/errored-Original_Inked_Artv15-ep00-gs00091
 * Saving SD model to D:\TrainedCheckpoints\errored-Original_Inked_Artv15-ep00-gs00091.ckpt
Traceback (most recent call last):
  File "D:\EveryDream2trainer\train.py", line 944, in <module>
    main(args)
  File "D:\EveryDream2trainer\train.py", line 871, in main
    raise ex
  File "D:\EveryDream2trainer\train.py", line 813, in main
    sample_generator.generate_samples(inference_pipe, global_step)
  File "D:\EveryDream2trainer\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\EveryDream2trainer\utils\sample_generator.py", line 189, in generate_samples
    images = pipe(prompt=prompts,
  File "D:\EveryDream2trainer\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\EveryDream2trainer\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 494, in __call__
    latents = self.prepare_latents(
  File "D:\EveryDream2trainer\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 386, in prepare_latents
    latents = torch.randn(shape, generator=generator, device=device, dtype=dtype)
TypeError: randn() received an invalid combination of arguments - got (tuple, generator=list, dtype=torch.dtype, device=torch.device), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 
This is my first time using EveryDream so it is likely it's something silly done on my end, but I am stuck. I tried to see if anyone else had reported the issue but didn't find anything to go off of. The first msg about "none of the inputs" seems to happen at every new epoch and doesn't seem related to everything else but I included it just in case...

**Comment by nawnie** [comment]
update your diffusers 

go to ed folder open cmd 

activate_venv

pip install -q diffusers[torch]==0.13.0

then your good to train, join the discord to get the latest updates :D

**Comment by what3vr** [comment]
Something so simple too!

Worked like a charm.

Cheers!

**Comment by nawnie** [comment]
May want to look at logging.md to see why it was needed its awesome
