### ISSUE TITLE
First samples for SD 2.1 training on RunPod aren't correct

### ISSUE THREAD

**Issue by Olaf-II** [victorchall/EveryDream2trainer#84]
![image](https://user-images.githubusercontent.com/93570328/220272825-3a008107-c72b-4809-bbeb-5084c7031bee.png)
These sort of images appear for the first samples, but the following ones are perfectly fine. Training on SD 2.1 on RunPod. Config file is trainSD21.json and these extra params:

--max_epochs 90 \
--sample_steps 93 \
--save_every_n_epochs 15 \
--lr 1.2e-6 \
--lr_scheduler constant \
--save_full_precision

**Comment by victorchall** [comment]
Is this still an issue?  Container has been updated in the last couple weeks, have not had any other reports of issues.
