### ISSUE TITLE
Converting to diffuser format a SD 1.5 based ckpt

### ISSUE THREAD

**Issue by lelapin123** [victorchall/EveryDream2trainer#90]
Hello,

when i try to convert to diffuser format a ckpt file with the command:
python utils/convert_original_stable_diffusion_to_diffusers.py --scheduler_type ddim ^
--original_config_file v1-inference.yaml ^
--image_size 512 ^
--checkpoint_path dreamshaper_331BakedVae.ckpt ^
--prediction_type epsilon ^
--upcast_attn False ^
--dump_path "ckpt_cache/dreamshaper_331BakedVae"

(dreamshaper_331BakedVae.ckpt is available on civitai and is based on SD 1,5)

I receive the following answer:

global_step key not found in model
load_state_dict from directly
Checkpoint dreamshaper_331BakedVae.ckpt has both EMA and non-EMA weights.
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
Traceback (most recent call last):
  File "D:\download\AI\EveryDream2trainer\utils\convert_original_stable_diffusion_to_diffusers.py", line 963, in <module>
    unet.load_state_dict(converted_unet_checkpoint)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias".
        Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight".

Is there is a way to fix this ?

**Comment by notintricate** [comment]
same problem

**Comment by defunky** [comment]
Get same issue with pastel model too, @victorchall is there any workaround for this, or are we limited to using directly sd ckpt only?

**Comment by notintricate** [comment]
> 

found a [workaround](https://github.com/d8ahazard/sd_dreambooth_extension/discussions/794). worked for me.

**Comment by nawnie** [comment]
the easiest work around without using other tools if downloading from HF directly is to use --resume_ckpt account/model 

example

--resume_ckpt stabilityai/stable-diffusion-2-1

this will work for any diffuser set on HF.

another but not "supported" work around would to use any other program or trainer that breaks models down to diffuers such as the webui or other CLI tools
