### ISSUE TITLE
What is EveryDream2trainer?

### ISSUE THREAD

**Issue by FurkanGozukara** [victorchall/EveryDream2trainer#95]
I am reading readme but no info available

Is this a new method like DreamBooth or else? What is it

What is the advantage compared to DreamBooth? 

ty for answers

**Comment by victorchall** [comment]
EveryDream is a general case fine tuner.  It does not explicitly implement the techniques from the Dreambooth paper. 

So there is no "class" or "token" or "regularization images". It simply trains image and caption pairings.

You can simulate Dreambooth somewhat by generating regularization images in an inference app and following some guidelines in the [Data Balancing](https://github.com/victorchall/EveryDream2trainer/blob/main/doc/BALANCING.md) readme to have them repeated a small fraction of the time using multiply.txt with a tiny number in it (like 0.05 if you're using several hundred regularization images). 

I suggest using other web scrape data, or ML data sets like FFHQ, Imagenet, Laion, Coco, or other publicly available ML image datasets in place of generated images out of Stable Diffusion for model preservation like Dreambooth does.  When you train on regularization images out of SD may reinforce bad habits.

**Comment by victorchall** [comment]
I added another doc here: https://github.com/victorchall/EveryDream2trainer/blob/main/doc/NOTDREAMBOOTH.md, hopefully makes it clear.

**Comment by FurkanGozukara** [comment]
> I added another doc here: https://github.com/victorchall/EveryDream2trainer/blob/main/doc/NOTDREAMBOOTH.md, hopefully makes it clear.

thanks a lot
i see you are simply using a lot of images to fine tune model. this is also possible with dreambooth extension of automatic1111 when you use captions and not use any classification images.  thank you for explanation

**Comment by lelapin123** [comment]
A list of specifications (hardware, software) could be useful
