### ISSUE TITLE
Is it possibile to train .safetensors instead of .ckpt?

### ISSUE THREAD

**Issue by destlaver** [victorchall/EveryDream2trainer#99]
most models from civitai are .safetensors, and I'd need to train one. Is it possibile wth everyDream? How?

**Comment by adamfils2** [comment]
Any update on this? @victorchall

**Comment by victorchall** [comment]
It's something I could look into adding but the easiest path might be to convert to diffusers using an existing script out there somewhere.

Reading the docs on diffusers it may just work out of the box for models hosted on hugginface as .safetensors.

`pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1")`
(automatically loads the safetensors version?)

https://huggingface.co/docs/diffusers/using-diffusers/using_safetensors

**Comment by victorchall** [comment]
Looked into this, it's still a bit of a mess because the single safetensors files are still in LDM format and it requires knowing a bunch of stuff about the model being loaded.  Not sure I'll get to this terrible soon.  Diffusers makes it inconvenient to load a local file even if some of the parts are there.

**Comment by vsemecky** [comment]
You can freely covert CPKT and SafeTensors to each other using the Model Convertor tool. https://github.com/Akegarasu/sd-webui-model-converter It's superfast and easy to use. I don't think it would be necessary for Safetensors to be directly supported in EveryDream.

**Comment by subpanic** [comment]
If you run the conversion script in the diffusers repo with safetensors enabled, it successfully generates a safetensors file that is able to be loaded and run inference on. I don't know if there's potential for issues with this route? If not, provides an easy solution for now - as long as you add safetensors package to your env, it works out of the box in with the existing everydream environment.

**Comment by victorchall** [comment]
This capability has been added.  .safetensors files that are a single file (LDM/compvis format, as opposed to diffusers), the conversion script has been updated to work with safetensors.   You still need to copy paste the conversion command. You still need to set the yaml and prediction type, as its not really possible to detect, or autodetection is very suspect.

Also, if you are not aware, the easiest way is to simply search on huggingface.co for the model name and see if someone already hosted it as the Diffusers format.  Try searching for the author's name, then also try the model name.  If there is a model already present with a model_config.json and folders called "vae" and "unet" and "text_encoder" etc that is a diffusers format.  Then just copy the "username/modelname" from the URL and use that for "resume_ckpt" in ED2.  It will autodownload, no conversions required.

Ex.  `"resume_ckpt": "Lykon/DreamShaper"`

That's it, no conversion required.  You can see here an example of a model that is already available for direct use.

![image](https://github.com/victorchall/EveryDream2trainer/assets/15839076/9c1bc2d4-1e9f-42b3-a576-ec1e10a39d67)

**Comment by victorchall** [comment]
This is solved now.  

Make sure to read the document for conversion carefully and use the `--from_safetensors` arg if the file you're converting is .safetensors and not .ckpt. 

https://github.com/victorchall/EveryDream2trainer/blob/main/doc/BASEMODELS.md

Example if your .safetensors file was trained from a SD1.x base model:
```python utils/convert_original_stable_diffusion_to_diffusers.py --scheduler_type ddim ^
--original_config_file v1-inference.yaml ^
--image_size 512 ^
--checkpoint_path my_sd15_model.safetensors ^
--from_safetensors ^
--to_safetensors ^
--prediction_type epsilon ^
--dump_path "ckpt_cache/my_sd15_model"```

Linux use \ instead of ^ for line continuation.
